/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 22.12.2025 16:32:26

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 10
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 20
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 17024;
#else
constexpr int kTensorArenaSize = 16000;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_ADD, OP_MEAN, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,975 } };
const TfArray<1, float> quant0_scale = { 1, { 0.047978907823562622, } };
const TfArray<1, int> quant0_zero = { 1, { 1 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 75, 13, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data2[2] = { 1, 2, };
const TfArray<1, int> tensor_dimension2 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[6] = { -1303, -539, 367, 438, 633, 215, };
const TfArray<1, int> tensor_dimension3 = { 1, { 6 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00014370189455803484, } };
const TfArray<1, int> quant3_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[6*32] = { 
  41, 72, -60, -59, -4, -16, 61, 61, -73, 0, 14, 60, 40, -17, 15, -11, -5, -60, 23, -125, 76, -42, -80, -22, 51, -21, 4, 0, 0, 0, -46, 21, 
  -45, 53, -58, 58, 28, -22, -69, 25, 48, 0, -82, 17, -6, 48, 27, 90, -74, -36, -15, 22, 52, -28, 48, -85, -50, 52, -1, 0, 0, 0, -78, 37, 
  46, -17, 18, -60, 34, -54, -46, -90, -60, 0, -4, 29, -104, 34, -75, 56, 43, 30, 10, -21, -25, 107, 94, -5, 29, -56, -4, 0, 0, 0, 9, -69, 
  17, 11, 33, -23, 30, -52, 83, -18, 43, 0, -59, -76, -103, -95, -74, -72, 21, 45, 25, 30, 25, -57, -24, -91, 35, -78, -12, 0, 0, 0, 53, 50, 
  66, -127, -64, 50, -54, -3, -106, 22, -8, 0, 46, 87, 24, 10, -121, -37, 18, -62, 1, -11, -111, -73, -50, 39, 35, 93, 3, 0, 0, 0, 41, -108, 
  -3, -22, 24, 61, -84, 40, -67, -55, 83, 0, 34, -85, 36, -55, -44, 11, -89, -95, -18, 6, -26, 31, -30, 63, -111, -45, 3, 0, 0, 0, 67, 22, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 6,32 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0073377029038965702, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[32] = { 1391, 440, 1604, 2388, 659, 1620, 814, 2088, 932, -353, 2225, 1939, 2077, 2130, 1749, -130, 424, 161, -1397, 1047, -890, 1000, 327, 2498, 830, 890, -733, 0, 1, -147, 1535, -640, };
const TfArray<1, int> tensor_dimension5 = { 1, { 32 } };
const TfArray<1, float> quant5_scale = { 1, { 4.374761920189485e-05, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[32*32] = { 
  -45, -49, 78, -64, 43, 19, 81, -4, 94, -10, -95, 38, -1, -3, -90, 27, -32, -29, 78, 19, -5, 11, 5, -29, 53, 4, 42, 16, 41, 47, 36, -65, 
  -34, 69, 67, -48, -56, -22, 56, -45, 4, 29, -24, -54, -29, -32, 7, 27, 55, -26, -52, -7, 55, 12, -16, -2, -2, 64, -32, 0, 41, 60, -61, 48, 
  97, -56, -105, 30, 51, 127, -76, 34, 29, 78, 51, 27, 97, -18, 40, 36, 36, 9, -11, -2, -36, -68, 61, -11, 17, -44, 3, -86, 2, -75, -1, -6, 
  -4, -15, 31, 65, 57, -56, -67, -15, -57, -75, 25, 4, -24, 62, -21, 41, 25, 24, -21, 40, -4, -3, -27, 15, 86, -6, 2, -18, -58, -22, 89, 28, 
  63, -25, 24, -31, -80, 10, -20, -8, 26, 67, 35, 54, 10, -58, 10, 75, 46, 59, 25, -19, 47, -65, -3, -30, -89, 35, 21, 37, 12, 32, -99, 51, 
  16, 9, 2, 36, 6, -30, 9, -19, -89, -60, 37, -42, -4, 62, 53, -67, 0, -13, 22, 73, -2, 69, -17, 24, -12, 35, -56, -68, -28, -21, 34, -3, 
  -27, 18, 54, 25, -31, 40, 81, -6, 44, 21, 60, 1, 16, -43, 40, -32, 19, -74, -19, 2, 30, 17, 75, -15, -38, 69, -64, -15, 6, 37, -87, -33, 
  -14, 6, 70, -40, 11, -72, 57, -59, -1, -13, 7, -44, -67, 3, -20, 18, -38, -6, 14, -7, 54, 48, -11, 46, 48, 42, -31, 9, 0, 87, -20, 14, 
  45, 47, -26, 78, 17, 37, -6, -24, -34, -55, 75, -10, 28, -10, 79, 26, 63, 20, -80, 56, 17, -27, 31, 1, 29, -39, -22, -88, -69, -19, 6, -22, 
  -6, -6, -1, -45, -10, -4, 8, -15, -33, 24, -39, -8, 38, -23, -20, 44, -9, -26, -42, 10, 0, -41, -15, -24, -15, -5, 8, -9, 2, -11, -44, -38, 
  0, -3, 16, 34, 67, 0, 21, 25, 9, -13, -66, 14, -37, 63, -5, -35, -80, -36, -3, 42, 16, 99, -16, -6, 77, 1, -5, 49, 1, 14, 40, -22, 
  -76, -35, 77, -29, 31, -46, 75, -2, 82, 49, -71, 44, -92, -13, -60, 43, -88, -47, 58, 5, 48, -8, -60, 48, 51, 20, 70, 81, 23, 47, 35, 0, 
  -34, 68, 16, 43, 16, -46, -12, -52, -59, -12, 5, -47, -52, 48, -13, -11, -29, 6, 37, 39, 22, 56, 24, 11, 40, 55, -27, 25, -6, 50, 68, -15, 
  28, 38, -15, -35, -49, -29, -20, 42, -30, -37, -63, -14, -25, 31, -53, 18, 11, 76, 17, -38, 21, 20, -18, 85, -16, 8, 46, 23, 43, 33, 15, 61, 
  -34, 76, 30, 2, -72, -50, 75, -66, -25, 17, -35, -78, -29, -14, -39, 43, 55, 9, -26, 8, 41, 17, -53, 5, -53, 38, 27, 17, -33, 69, -29, 75, 
  15, 26, 13, -5, -46, -33, -8, 28, -4, 0, -17, 44, 5, -18, -49, 63, 15, 63, -8, -30, 10, -74, -97, 52, -50, -23, 69, 69, -24, 14, -32, -4, 
  -41, 2, -6, -30, 18, 50, 68, 71, 71, 83, -63, 66, 14, -4, -43, 53, -64, -36, 90, 20, 24, 28, 25, 11, 1, -27, 29, -11, 101, 12, -49, -49, 
  50, -58, -12, 16, -92, 24, -35, 68, 43, 46, 62, 62, 43, -70, 39, 26, 38, -9, -6, -60, 8, -112, 82, 11, -108, -47, 48, -31, 36, 36, -34, -35, 
  -5, -16, 3, 20, -49, -6, -17, -37, -21, -37, 31, 10, -21, -22, -38, -1, 5, 0, 11, -49, -39, -54, 19, -30, 33, 0, 20, 38, 44, -19, -19, 24, 
  52, -58, -5, 48, 18, 19, -62, -19, -11, -35, 57, 41, 5, -18, 37, -7, 63, 26, -16, 27, -30, 22, 41, 51, 59, -29, 48, -60, -41, 16, -16, 43, 
  2, 23, 69, -24, -40, 9, 78, -58, 33, -4, 52, -70, -64, -74, -53, -12, 19, -10, 2, 4, 5, 22, -20, 40, 10, 25, 6, 37, -18, 62, -73, 40, 
  -13, 10, -4, -92, -68, 68, -18, 73, 27, 49, -56, -2, -47, 1, -1, 12, 18, 73, -17, -96, -23, 9, -59, 46, -52, 18, 12, 43, 70, -30, -31, -51, 
  57, -24, -66, -25, -38, 1, -16, 32, 43, 27, -74, 45, -39, -4, -15, 35, -10, 100, 48, -109, -11, -62, -36, 23, -106, -9, 76, -4, -26, 35, 5, 57, 
  6, -8, 28, -13, 87, 24, 17, 1, -84, -58, 18, -21, -22, 57, 22, -9, -43, -14, 32, 73, -13, 83, -39, -18, 29, -42, -14, -42, -31, 4, 21, 4, 
  -35, -12, 80, -26, 9, -4, 81, -5, 104, 40, -45, 64, -4, 7, 15, -14, -52, -48, 3, 37, 37, 5, 28, -52, -29, -18, 73, 92, 55, 62, -30, -47, 
  -58, -36, 47, 37, 40, -98, -14, -30, 24, -69, -75, 53, 1, -17, -61, 12, -55, 44, 54, -27, 43, 26, -26, 48, 45, -15, 30, 50, -21, 13, 7, 62, 
  36, -49, 40, -38, -15, -50, 32, -10, 36, -35, -34, 42, -31, -44, 34, 6, -47, -34, -36, 5, -53, -50, 31, 36, -11, 34, 14, -49, 24, -35, -35, 1, 
  43, 3, -46, 7, 28, 13, -18, -41, -34, -30, -42, -13, 3, -8, -44, -31, 39, -43, 1, 4, -21, -34, -31, -41, -33, 20, 43, 6, -2, -14, 9, -38, 
  32, -25, -47, 18, 19, -42, -25, -40, 22, -11, -3, -12, 14, -20, -8, -44, -11, -10, 47, -20, -14, -23, 3, 4, -41, -42, -43, -30, 14, 9, 9, -35, 
  39, -26, -38, -26, -45, -41, 24, 33, -14, -39, 4, 24, -6, 34, -35, 38, -49, -47, 21, 1, 7, 11, -13, -35, -28, -19, -25, 6, -16, -12, 14, -6, 
  67, 1, -38, 25, 39, 5, -70, -17, -6, 46, 0, 44, 79, 83, 77, -38, 15, -54, 52, 44, 28, 9, 44, -35, 30, -34, 39, -58, -30, -44, 67, -68, 
  41, 57, 10, 59, -3, 0, 23, -27, -6, 26, 78, -39, 20, -15, 79, 17, 77, -41, -69, 53, 13, 24, 19, -24, -42, -12, -76, 13, -21, 14, -24, 27, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 32,32 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0063946014270186424, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[32] = { -369, -4204, -8331, 954, -502, 682, -5631, 2971, -3975, -2760, 4001, 4746, -1644, 5166, 2378, 892, 1999, 4546, 4930, -260, 5482, -4932, 283, -466, -107, -2721, 6355, -3740, -943, -4032, 5377, -3391, };
const TfArray<32, float> quant7_scale = { 32, { 0.00012068408977938816, 0.00012659092317335308, 9.9483571830205619e-05, 0.00016578064241912216, 0.00011601003643590957, 0.00011337432806612924, 0.00010985646804329008, 0.00012334891653154045, 0.00011711747356457636, 0.00012331618927419186, 0.00012032232916681096, 0.00013734461390413344, 0.0001248863700311631, 0.0001440793857909739, 0.00012131920084357262, 0.0001920720242196694, 0.00011405528493924066, 0.00017109423060901463, 0.00017001150990836322, 0.00015729751612525433, 0.00011059567623306066, 0.00011718370660673827, 0.00015177146997302771, 0.00012054393300786614, 0.0001370290556224063, 0.00012729098671115935, 0.00020616585970856249, 0.00018607910897117108, 0.00010103183740284294, 0.00013807060895487666, 0.00011294458818156272, 0.00018010236090049148, } };
const TfArray<32, int> quant7_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[32*1*1*24] = { 
  /* [0][0][][] */ -48,21,32,-1,85,-22,103,-101,-38,-63,-117,-62,19,-40,87,-34,-29,7,92,53,92,-42,127,38, 
  /* [1][0][][] */ 99,-8,65,127,19,-45,-111,89,78,50,3,-5,45,-29,6,-12,10,-36,-31,11,74,7,4,-40, 
  /* [2][0][][] */ -13,-127,-61,57,-89,77,-31,109,77,120,86,121,67,-34,53,40,58,121,-60,73,-52,58,-69,77, 
  /* [3][0][][] */ -45,18,-24,40,-42,-85,21,14,-19,-2,-94,-83,-8,20,-27,64,-8,-74,127,30,1,14,61,41, 
  /* [4][0][][] */ -11,12,-58,-42,36,-64,-3,-89,59,75,9,-95,15,84,4,122,-83,17,35,-127,32,81,-9,79, 
  /* [5][0][][] */ -70,98,88,-57,38,-15,106,-127,-82,-43,-55,-12,-91,39,93,-38,58,12,51,41,74,-9,14,-81, 
  /* [6][0][][] */ 127,-6,105,37,-72,-1,-51,67,85,107,50,23,30,54,-93,-35,16,86,9,118,-40,51,-116,-97, 
  /* [7][0][][] */ -8,-88,11,-22,107,108,34,-127,-36,-82,46,71,-24,15,26,-72,14,-56,-47,27,30,-27,102,-89, 
  /* [8][0][][] */ 39,2,76,-85,-15,-15,-3,5,-33,46,90,127,-26,44,-35,-65,91,8,-31,42,58,-9,12,-34, 
  /* [9][0][][] */ 17,57,127,-26,31,18,9,39,-21,-4,37,36,-53,56,64,-100,5,34,-31,16,73,-26,12,-75, 
  /* [10][0][][] */ -118,60,35,61,-97,-71,79,-29,-18,1,-106,-76,-63,-95,-5,44,-1,-5,98,127,-92,13,-21,22, 
  /* [11][0][][] */ -41,-70,-14,-127,3,13,35,-90,-108,31,81,103,-15,25,-15,-44,76,-48,-69,19,33,-15,47,-103, 
  /* [12][0][][] */ -72,63,50,-65,-95,0,127,-34,-39,-36,21,-54,-63,-93,32,45,5,36,49,126,40,-2,47,43, 
  /* [13][0][][] */ -15,-108,-24,-9,79,-53,-9,-97,53,-11,-53,-74,-15,127,-34,21,-41,10,-1,-83,14,44,10,35, 
  /* [14][0][][] */ -56,92,-15,-44,-24,-93,97,-55,-55,-27,-77,-65,-69,-76,-18,68,18,-49,86,127,28,-6,-17,51, 
  /* [15][0][][] */ -12,-62,-33,26,7,59,-19,-19,-16,13,-88,59,48,8,127,-49,32,-17,7,-49,10,-72,50,-30, 
  /* [16][0][][] */ -99,-29,-35,127,-58,-77,115,58,-51,-22,-98,-78,-23,-110,79,18,39,34,70,78,-87,-32,46,18, 
  /* [17][0][][] */ 34,-127,-85,67,104,7,-35,32,-43,-38,-60,18,30,-27,84,-23,35,-97,-18,-33,2,-62,110,-86, 
  /* [18][0][][] */ -6,-127,-103,-115,-44,52,-53,-85,7,56,48,105,-15,-53,48,45,32,-29,-21,-15,-31,11,6,-39, 
  /* [19][0][][] */ -22,29,-28,-7,-8,-89,25,-58,127,10,-73,-66,-33,-20,-9,52,-6,-28,77,50,-10,83,-4,66, 
  /* [20][0][][] */ -79,83,-44,15,-38,18,-42,-23,77,-4,73,-48,71,-54,64,-27,-78,-18,54,-22,-83,37,-127,-64, 
  /* [21][0][][] */ 19,-21,-28,-45,23,-68,-57,25,127,117,48,-98,73,108,-11,77,-27,77,-19,-44,31,60,-41,122, 
  /* [22][0][][] */ -89,123,42,-60,-127,-24,61,-19,-27,35,-48,-29,-63,-69,-45,102,32,72,68,122,-20,51,-37,-19, 
  /* [23][0][][] */ 82,-114,-127,100,32,60,-60,42,-93,-5,-102,79,42,-48,85,-52,71,-59,-19,-5,-16,17,117,-27, 
  /* [24][0][][] */ -6,-24,-44,-14,15,-29,-9,-59,62,34,23,-59,33,30,8,113,-43,36,-3,-127,17,72,-34,59, 
  /* [25][0][][] */ 25,-32,50,44,-16,-69,-50,127,102,95,-8,-29,53,31,-90,-58,66,15,2,47,-26,30,-76,-16, 
  /* [26][0][][] */ -8,-127,-44,-19,-20,75,-34,-64,-34,16,2,66,-12,20,12,-30,35,-62,-35,-2,-51,-18,50,-87, 
  /* [27][0][][] */ 127,-85,-15,25,14,21,-19,-17,2,73,51,55,49,8,-24,-63,90,-24,-28,40,-102,8,27,-16, 
  /* [28][0][][] */ 72,-97,115,-98,53,-31,-13,-47,-2,77,53,104,-39,33,60,-127,65,-3,-61,52,47,12,43,-94, 
  /* [29][0][][] */ 56,-56,27,50,-66,-24,-83,65,27,97,-20,65,75,5,20,-28,127,11,-43,85,-34,24,-41,-19, 
  /* [30][0][][] */ -15,-19,-60,-11,127,-72,-72,-81,30,-58,-32,-90,4,100,-13,76,-121,56,1,-96,78,34,6,37, 
  /* [31][0][][] */ 51,-11,-86,127,-19,-58,12,127,-57,16,-73,-6,54,6,25,-12,40,-42,22,-19,-7,-35,64,3, 
};
const TfArray<4, int> tensor_dimension8 = { 4, { 32,1,1,24 } };
const TfArray<32, float> quant8_scale = { 32, { 0.0051290737465023994, 0.0053801140747964382, 0.0042280517518520355, 0.0070456769317388535, 0.0049304263666272163, 0.0048184087499976158, 0.0046688998118042946, 0.0052423290908336639, 0.0049774926155805588, 0.0052409376949071884, 0.0051136990077793598, 0.0058371457271277905, 0.0053076706826686859, 0.0061233737505972385, 0.0051560658030211926, 0.0081630609929561615, 0.0048473495990037918, 0.0072715049609541893, 0.0072254892438650131, 0.006685144267976284, 0.0047003161162137985, 0.0049803075380623341, 0.0064502870664000511, 0.0051231170073151588, 0.0058237346820533276, 0.0054098670370876789, 0.0087620485574007034, 0.0079083619639277458, 0.0042938529513776302, 0.0058680009096860886, 0.004800145048648119, 0.0076543502509593964, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[24] = { 2835, 5178, -2696, -242, -1483, 1386, -2564, 1889, -699, 1020, -6666, 135, -3079, -4393, 6733, -1158, 3634, -2070, -1180, -639, -1067, -2100, -5345, 7202, };
const TfArray<1, int> tensor_dimension9 = { 1, { 24 } };
const TfArray<24, float> quant9_scale = { 24, { 0.00020042680262122303, 0.00013962383673060685, 0.00018087153148371726, 0.00074961985228583217, 0.00020602902804967016, 0.00021088916400913149, 0.00013552930613514036, 0.00028310710331425071, 0.00015194232400972396, 0.00028509297408163548, 0.0001182465348392725, 0.00056675885571166873, 0.00024359395320061594, 7.3299946961924434e-05, 0.00018433741934131831, 0.00032865413231775165, 0.00020184210734441876, 0.00012588432582560927, 0.00033907697070389986, 0.00014547923638019711, 0.00017901466344483197, 0.0002625930355861783, 9.1269321274012327e-05, 0.00015991338295862079, } };
const TfArray<24, int> quant9_zero = { 24, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[1*3*3*24] = { 
  /* [0][0][][] */ -86,98,41,54,-8,-5,69,-116,-3,-127,71,28,65,3,-11,7,-127,-74,82,-127,0,127,36,-32, 7,-11,102,-31,111,-85,66,87,70,-32,113,53,25,117,-124,110,-57,-117,106,-54,4,16,95,-57, -10,61,92,6,-88,1,-29,21,-18,1,-45,-41,-19,127,4,89,-24,-7,11,-22,15,-5,29,-18, 
  /* [0][1][][] */ 26,-31,109,91,1,83,126,-85,-67,-47,71,17,127,11,-88,127,-20,-20,80,21,-27,71,127,-127, -87,-121,21,-63,123,-55,127,127,127,25,127,127,37,107,-127,100,-60,-45,127,38,5,58,106,-46, -64,-121,127,-127,85,-29,-10,-19,18,41,-47,-73,51,31,66,126,69,107,56,10,110,-26,15,-21, 
  /* [0][2][][] */ 71,-110,-44,73,-95,127,63,-55,-119,9,-14,16,73,99,-90,116,34,68,28,48,18,21,103,-84, -127,-30,-2,-58,127,-19,66,89,113,63,90,67,20,61,-49,73,-63,-8,92,90,-127,62,72,-1, -38,-127,122,-47,17,-12,13,-26,75,8,35,-6,11,111,9,84,91,127,47,15,47,13,47,-16, 
};
const TfArray<4, int> tensor_dimension10 = { 4, { 1,3,3,24 } };
const TfArray<24, float> quant10_scale = { 24, { 0.0085181389003992081, 0.0059340130537748337, 0.007687040138989687, 0.031858842819929123, 0.0087562333792448044, 0.0089627895504236221, 0.0057599954307079315, 0.01203205157071352, 0.006457548588514328, 0.012116451747715473, 0.0050254776142537594, 0.024087252095341682, 0.010352742858231068, 0.0031152477022260427, 0.0078343404456973076, 0.013967800885438919, 0.0085782893002033234, 0.0053500835783779621, 0.014410771429538727, 0.0061828675679862499, 0.0076081231236457825, 0.011160203255712986, 0.0038789461832493544, 0.0067963185720145702, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant9_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data11[24] = { -4661, -2480, -9766, -2585, -1941, 6665, -1607, -4628, 1008, 1222, -3559, -4584, 779, 651, 8573, -1687, 8709, -5897, -2753, -3450, -7134, 3562, -3200, -346, };
const TfArray<24, float> quant11_scale = { 24, { 9.8777236416935921e-05, 0.00011063602869398892, 7.1793998358771205e-05, 5.697527012671344e-05, 9.363659773953259e-05, 0.00011576915858313441, 0.00018768968584481627, 0.00013246567687019706, 0.00014789823035243899, 0.00014414030010811985, 0.00012414372758939862, 9.7280535555910319e-05, 0.00011592225200729445, 0.00019846638315357268, 0.00010614092752803117, 9.9580196547321975e-05, 0.00010161323007196188, 0.00023045108537189662, 0.00010527940321480855, 0.00013479340123012662, 0.00012921373127028346, 0.00012470076035242528, 0.00020305595535319299, 0.00018899489077739418, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant9_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data12[24*1*1*16] = { 
  /* [0][0][][] */ 70,28,-37,-97,0,127,-87,21,54,86,36,3,12,-73,5,12, 
  /* [1][0][][] */ -127,-14,-61,21,-12,-9,9,-46,113,103,27,126,69,37,-95,64, 
  /* [2][0][][] */ -22,-57,8,8,101,127,-62,-88,21,7,106,34,88,-22,5,-112, 
  /* [3][0][][] */ -5,59,-127,51,-62,-112,32,84,116,-50,-15,-51,-82,18,-75,-14, 
  /* [4][0][][] */ 127,70,61,22,-64,-53,31,-55,-60,-1,-64,59,8,-108,30,92, 
  /* [5][0][][] */ 105,-75,31,-18,55,64,19,-78,-62,59,-77,-11,-31,-127,-108,-36, 
  /* [6][0][][] */ -76,127,86,87,-82,60,-17,-43,-7,28,-20,-20,4,-77,8,89, 
  /* [7][0][][] */ 5,38,-4,24,28,-4,-9,-70,-4,-42,-11,-53,29,127,-41,21, 
  /* [8][0][][] */ 56,29,5,48,34,-73,-100,-127,1,-9,55,-83,8,17,-55,28, 
  /* [9][0][][] */ -32,-50,39,-99,71,-72,-94,-34,6,33,-87,15,-30,127,-73,15, 
  /* [10][0][][] */ 3,-62,-32,42,127,27,-22,-41,-20,28,80,56,30,2,-101,62, 
  /* [11][0][][] */ 9,33,23,-64,55,-61,-127,-40,-38,39,-126,54,32,55,40,15, 
  /* [12][0][][] */ -127,12,14,-48,1,-83,-50,99,-45,37,-29,-123,60,84,-91,-81, 
  /* [13][0][][] */ 62,-95,4,91,38,-29,-29,-57,-127,-10,9,115,-17,21,20,-61, 
  /* [14][0][][] */ -12,41,-33,68,-4,-92,-2,-73,-71,-127,56,43,-3,-53,-99,0, 
  /* [15][0][][] */ 41,-85,9,96,-127,-32,25,-6,-41,34,24,-27,-53,-60,81,-13, 
  /* [16][0][][] */ -116,-61,-127,-65,18,-26,87,-32,-101,73,-71,4,54,-95,-60,-48, 
  /* [17][0][][] */ -25,59,-14,127,-27,67,38,-2,24,13,-2,-7,56,17,47,-41, 
  /* [18][0][][] */ -127,72,6,32,-45,0,55,1,26,93,-37,-32,40,-65,2,-3, 
  /* [19][0][][] */ -56,24,-45,-57,67,31,-80,-75,106,127,89,-20,67,-70,-6,57, 
  /* [20][0][][] */ 78,-1,-97,-17,-19,96,-67,127,-60,51,13,25,44,108,3,-34, 
  /* [21][0][][] */ 21,68,-127,-57,53,-86,-115,22,29,-23,16,17,55,-104,-116,3, 
  /* [22][0][][] */ 12,-19,28,55,23,-32,-14,61,30,45,-25,19,-127,89,19,56, 
  /* [23][0][][] */ 9,-34,-124,-127,30,53,-10,-5,-36,43,36,-50,-39,70,33,23, 
};
const TfArray<4, int> tensor_dimension12 = { 4, { 24,1,1,16 } };
const TfArray<24, float> quant12_scale = { 24, { 0.0041980324313044548, 0.0047020311467349529, 0.0030512448865920305, 0.0024214489385485649, 0.0039795553311705589, 0.004920189268887043, 0.0079768113791942596, 0.0056297914125025272, 0.0062856744043529034, 0.0061259623616933823, 0.0052761086262762547, 0.0041344226337969303, 0.0049266954883933067, 0.0084348209202289581, 0.0045109894126653671, 0.0042321584187448025, 0.0043185623362660408, 0.009794170968234539, 0.0044743744656443596, 0.0057287192903459072, 0.0054915836080908775, 0.0052997823804616928, 0.0086298780515789986, 0.0080322828143835068, } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&g0::quant9_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data13[16] = { -4337, 6562, -5578, 908, -2366, -1708, -1391, -233, 4271, -5086, -5065, 1224, -2600, 8443, 5287, -3547, };
const TfArray<1, int> tensor_dimension13 = { 1, { 16 } };
const TfArray<16, float> quant13_scale = { 16, { 0.00014246867795009166, 9.0688881755340844e-05, 0.00010440444748383015, 0.00010583660332486033, 0.00019109132699668407, 0.00028289578040130436, 0.00012232961307745427, 0.00014381365326698869, 0.00012849165068473667, 0.00013831982505507767, 0.0001070871512638405, 0.00010048039257526398, 0.00011647711653495207, 0.00014491337060462683, 0.00010158855729969218, 0.00020633215899579227, } };
const TfArray<16, int> quant13_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data14[1*3*3*16] = { 
  /* [0][0][][] */ 11,-75,21,24,-77,60,43,-114,-127,17,-2,54,30,-25,53,-35, 127,-127,-5,-92,115,-57,-44,30,17,30,127,-43,-26,-62,-116,71, -37,-6,5,44,-30,14,11,37,25,7,25,-4,82,27,22,34, 
  /* [0][1][][] */ 18,-44,86,-58,-17,112,127,-127,-73,74,2,55,40,-53,62,46, 74,-53,8,-88,127,-17,-45,70,-61,103,99,-127,4,-127,-127,107, -21,9,-8,54,33,23,-31,54,63,23,6,21,127,15,-16,75, 
  /* [0][2][][] */ 49,-43,127,-127,28,127,61,-105,-25,40,18,107,47,-35,41,-45, 62,59,-56,-76,70,33,-28,57,-60,127,52,-123,-48,-72,-84,127, 31,39,55,36,51,4,-30,36,38,32,-9,-61,124,19,-7,88, 
};
const TfArray<4, int> tensor_dimension14 = { 4, { 1,3,3,16 } };
const TfArray<16, float> quant14_scale = { 16, { 0.006054918747395277, 0.0038542773108929396, 0.0044371890835464001, 0.0044980556704103947, 0.008121381513774395, 0.012023070827126503, 0.005199008621275425, 0.0061120800673961639, 0.0054608951322734356, 0.0058785923756659031, 0.0045512039214372635, 0.004270416684448719, 0.0049502775073051453, 0.0061588180251419544, 0.0043175136670470238, 0.0087691163644194603, } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&g0::quant13_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data15[16] = { -6127, -2222, -2718, -7570, -4701, 1411, 2045, 3781, -6408, 2736, 2287, -4202, 209, -2045, 2885, -3655, };
const TfArray<16, float> quant15_scale = { 16, { 0.00023061421234160662, 0.00014710964751429856, 0.00015953501861076802, 0.00013786890485789627, 0.00018205592641606927, 0.00022804761829320341, 0.00017318985192105174, 0.00015835193335078657, 0.0001455612073186785, 0.00022025713406037539, 0.00018487610213924199, 0.0001702459849184379, 0.00029645225731655955, 0.00023949045862536877, 0.00020126996969338506, 0.00012481740850489587, } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data16[16*1*1*16] = { 
  /* [0][0][][] */ 87,14,127,-64,68,61,-16,-27,-74,18,-28,51,34,33,-69,-39, 
  /* [1][0][][] */ 91,-66,-4,59,58,-9,45,127,-5,64,-93,-43,85,-28,119,-70, 
  /* [2][0][][] */ -79,53,32,127,78,99,-37,-56,-123,63,-70,-55,75,-24,45,-95, 
  /* [3][0][][] */ 28,49,-127,-46,75,93,100,26,46,-7,13,13,13,43,25,-101, 
  /* [4][0][][] */ 48,-99,55,17,127,-92,39,21,82,-2,-92,-32,62,-1,-82,-29, 
  /* [5][0][][] */ -59,-27,-7,-29,34,13,20,17,-61,-37,-7,-28,25,-127,12,24, 
  /* [6][0][][] */ 54,-31,-39,-49,7,27,-95,3,6,-127,-86,19,-63,43,45,77, 
  /* [7][0][][] */ -73,39,-82,-49,-127,-44,-116,115,18,63,17,77,-51,55,-51,-29, 
  /* [8][0][][] */ 120,-88,70,-13,-20,-102,79,1,-28,-21,55,127,-17,0,61,60, 
  /* [9][0][][] */ -19,-37,58,-38,-3,25,-49,2,6,-56,-127,-103,75,-15,58,23, 
  /* [10][0][][] */ -31,127,3,-24,-83,46,-119,-5,62,11,-28,-41,56,-21,52,-11, 
  /* [11][0][][] */ 21,109,-60,127,-108,110,58,-89,6,18,-9,74,20,-12,-32,-71, 
  /* [12][0][][] */ -25,-49,-5,-37,28,45,25,-32,-12,18,1,-127,7,12,-13,82, 
  /* [13][0][][] */ -127,9,-12,45,3,-30,74,-23,-59,32,41,8,42,-31,21,52, 
  /* [14][0][][] */ -33,6,1,87,10,-80,24,23,42,71,31,-9,-26,-127,-99,-53, 
  /* [15][0][][] */ 39,-50,11,95,87,4,-127,-90,-74,4,-80,25,109,33,-43,-18, 
};
const TfArray<4, int> tensor_dimension16 = { 4, { 16,1,1,16 } };
const TfArray<16, float> quant16_scale = { 16, { 0.0098011037334799767, 0.0062521598301827908, 0.0067802378907799721, 0.0058594285510480404, 0.0077373767271637917, 0.0096920235082507133, 0.0073605682700872421, 0.0067299571819603443, 0.0061863511800765991, 0.00936092808842659, 0.0078572342172265053, 0.0072354539297521114, 0.012599220499396324, 0.010178344324231148, 0.0085539733991026878, 0.005304739810526371, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data17[16] = { -1191, -1384, 788, -1652, 3211, 1254, 1044, -1420, -592, -3862, 2907, 4763, -1969, 1783, -4636, 979, };
const TfArray<16, float> quant17_scale = { 16, { 0.00033930156496353447, 0.00013406365178525448, 0.00017015865887515247, 0.00020678061991930008, 0.00030622491613030434, 0.00027557992143556476, 0.00018740184896159917, 0.00023472841712646186, 0.00018624876975081861, 0.00021597745944745839, 0.00015097488358151168, 0.00022328553313855082, 0.00025187095161527395, 0.00033934967359527946, 0.00019696175877470523, 0.00031971783027984202, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data18[1*3*3*16] = { 
  /* [0][0][][] */ 96,-111,55,117,-127,2,127,36,29,75,-74,-127,-67,0,25,127, 30,127,52,-92,3,37,-59,77,-115,-9,-7,31,117,-16,48,-2, 127,-98,-127,8,-30,-28,-66,-41,52,17,-96,-32,-65,61,-26,-64, 
  /* [0][1][][] */ 73,58,6,-1,-27,30,112,-120,44,127,66,-35,61,-36,127,40, -29,127,21,60,-57,-53,-55,-96,-6,2,-82,5,-7,-127,61,-64, -75,-61,-89,19,-93,-72,-10,-5,20,41,-127,-48,54,40,83,-126, 
  /* [0][2][][] */ 54,-29,-123,-127,-64,-35,74,127,43,25,116,-85,87,-29,74,-93, 15,14,-14,102,28,89,-14,86,51,17,-81,-41,-127,-13,-45,-27, -25,-31,116,29,23,-127,-35,63,-127,21,-22,-44,16,46,73,14, 
};
const TfArray<16, float> quant18_scale = { 16, { 0.014420316554605961, 0.0056977048516273499, 0.0072317426092922688, 0.0087881758809089661, 0.013014558702707291, 0.011712145991623402, 0.0079645784571766853, 0.0099759576842188835, 0.0079155722633004189, 0.0091790417209267616, 0.0064164325594902039, 0.0094896350055932999, 0.010704515501856804, 0.014422360807657242, 0.0083708744496107101, 0.013588007539510727, } };
const TfLiteAffineQuantization quant18 = { (TfLiteFloatArray*)&quant18_scale, (TfLiteIntArray*)&g0::quant13_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data19[16] = { -735, 497, 88, -426, -2108, -1527, 931, -834, 390, -61, -29, -21, 248, 658, -1117, -2061, };
const TfArray<16, float> quant19_scale = { 16, { 0.00016516343748662621, 0.00025308821932412684, 0.00020587652397807688, 0.00013330981892067939, 0.00012227645493112504, 0.00017569732153788209, 0.00010483441292308271, 0.00030621082987636328, 0.00020177550322841853, 0.00020073424093425274, 0.00019716605311259627, 0.00010464191291248426, 0.0001371053367620334, 0.00011328457912895828, 0.00022162192908581346, 0.00020125627634115517, } };
const TfLiteAffineQuantization quant19 = { (TfLiteFloatArray*)&quant19_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data20[16*3*3*1] = { 
  /* [0][0][][] */ 1, 12, -55, 
  /* [0][1][][] */ 49, -51, -26, 
  /* [0][2][][] */ 127, -53, -6, 
  /* [1][0][][] */ -66, 28, -53, 
  /* [1][1][][] */ -68, 127, -61, 
  /* [1][2][][] */ 31, 77, -74, 
  /* [2][0][][] */ 90, -66, -82, 
  /* [2][1][][] */ 5, -96, 14, 
  /* [2][2][][] */ 26, -127, 50, 
  /* [3][0][][] */ -105, -11, 124, 
  /* [3][1][][] */ -18, 73, 117, 
  /* [3][2][][] */ 10, 127, 60, 
  /* [4][0][][] */ 103, 79, -69, 
  /* [4][1][][] */ 90, 76, -48, 
  /* [4][2][][] */ 127, 93, 16, 
  /* [5][0][][] */ -64, 76, -65, 
  /* [5][1][][] */ -29, 114, -127, 
  /* [5][2][][] */ -9, 62, -114, 
  /* [6][0][][] */ -2, -107, -111, 
  /* [6][1][][] */ -119, -127, -73, 
  /* [6][2][][] */ 66, -110, 5, 
  /* [7][0][][] */ -9, 64, -23, 
  /* [7][1][][] */ -52, -61, 127, 
  /* [7][2][][] */ 30, -29, -29, 
  /* [8][0][][] */ 88, -127, -32, 
  /* [8][1][][] */ 30, -62, -125, 
  /* [8][2][][] */ 1, 110, -85, 
  /* [9][0][][] */ -127, 88, -35, 
  /* [9][1][][] */ -32, 86, -47, 
  /* [9][2][][] */ -58, 94, -10, 
  /* [10][0][][] */ 32, -40, -127, 
  /* [10][1][][] */ -31, 60, -117, 
  /* [10][2][][] */ -70, 77, -63, 
  /* [11][0][][] */ 44, -127, -102, 
  /* [11][1][][] */ 56, -125, -124, 
  /* [11][2][][] */ 98, -42, -67, 
  /* [12][0][][] */ -5, 108, 65, 
  /* [12][1][][] */ 54, 127, 31, 
  /* [12][2][][] */ 44, 79, -29, 
  /* [13][0][][] */ -75, 0, 123, 
  /* [13][1][][] */ -44, 30, 127, 
  /* [13][2][][] */ 14, 37, 55, 
  /* [14][0][][] */ 111, 52, -122, 
  /* [14][1][][] */ -35, -48, 30, 
  /* [14][2][][] */ -67, -127, 99, 
  /* [15][0][][] */ -22, -60, 19, 
  /* [15][1][][] */ -35, -44, 29, 
  /* [15][2][][] */ -127, 10, 120, 
};
const TfArray<4, int> tensor_dimension20 = { 4, { 16,3,3,1 } };
const TfArray<16, float> quant20_scale = { 16, { 0.0034424175973981619, 0.0052749891765415668, 0.0042909798212349415, 0.0027785087004303932, 0.002548546064645052, 0.003661970142275095, 0.0021850103512406349, 0.0063821966759860516, 0.0042055044323205948, 0.0041838018223643303, 0.0041094319894909859, 0.0021809982135891914, 0.0028576168697327375, 0.0023611329961568117, 0.0046191532164812088, 0.0041946824640035629, } };
const TfLiteAffineQuantization quant20 = { (TfLiteFloatArray*)&quant20_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,75,13,1 } };
const TfArray<4, int> tensor_dimension22 = { 4, { 1,38,7,16 } };
const TfArray<1, float> quant22_scale = { 1, { 0.023529412224888802, } };
const TfArray<1, int> quant22_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&quant22_zero, 0 };
const TfArray<1, float> quant24_scale = { 1, { 0.081556454300880432, } };
const TfArray<1, int> quant24_zero = { 1, { 2 } };
const TfLiteAffineQuantization quant24 = { (TfLiteFloatArray*)&quant24_scale, (TfLiteIntArray*)&quant24_zero, 0 };
const TfArray<4, int> tensor_dimension26 = { 4, { 1,19,4,16 } };
const TfArray<4, int> tensor_dimension27 = { 4, { 1,19,4,24 } };
const TfArray<4, int> tensor_dimension28 = { 4, { 1,10,2,24 } };
const TfArray<4, int> tensor_dimension29 = { 4, { 1,10,2,32 } };
const TfArray<2, int> tensor_dimension30 = { 2, { 1,32 } };
const TfArray<1, float> quant30_scale = { 1, { 0.0068413363769650459, } };
const TfLiteAffineQuantization quant30 = { (TfLiteFloatArray*)&quant30_scale, (TfLiteIntArray*)&g0::quant22_zero, 0 };
const TfArray<1, float> quant31_scale = { 1, { 0.019584042951464653, } };
const TfLiteAffineQuantization quant31 = { (TfLiteFloatArray*)&quant31_scale, (TfLiteIntArray*)&g0::quant22_zero, 0 };
const TfArray<2, int> tensor_dimension32 = { 2, { 1,6 } };
const TfArray<1, float> quant32_scale = { 1, { 0.077511593699455261, } };
const TfArray<1, int> quant32_zero = { 1, { 7 } };
const TfLiteAffineQuantization quant32 = { (TfLiteFloatArray*)&quant32_scale, (TfLiteIntArray*)&quant32_zero, 0 };
const TfArray<1, float> quant33_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant33 = { (TfLiteFloatArray*)&quant33_scale, (TfLiteIntArray*)&g0::quant22_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 21 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 2,2, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 21,20,19 } };
const TfArray<1, int> outputs1 = { 1, { 22 } };
const TfLiteDepthwiseConvParams opdata2 = { kTfLitePaddingSame, 1,1, 1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs2 = { 3, { 22,18,17 } };
const TfArray<1, int> outputs2 = { 1, { 23 } };
const TfLiteConvParams opdata3 = { kTfLitePaddingSame, 1,1, kTfLiteActNone, 1,1 };
const TfArray<3, int> inputs3 = { 3, { 23,16,15 } };
const TfArray<1, int> outputs3 = { 1, { 24 } };
const TfLiteAddParams opdata4 = { kTfLiteActRelu6 };
const TfArray<2, int> inputs4 = { 2, { 24,22 } };
const TfArray<1, int> outputs4 = { 1, { 25 } };
const TfLiteDepthwiseConvParams opdata5 = { kTfLitePaddingSame, 2,2, 1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 25,14,13 } };
const TfArray<1, int> outputs5 = { 1, { 26 } };
const TfLiteConvParams opdata6 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs6 = { 3, { 26,12,11 } };
const TfArray<1, int> outputs6 = { 1, { 27 } };
const TfLiteDepthwiseConvParams opdata7 = { kTfLitePaddingSame, 2,2, 1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs7 = { 3, { 27,10,9 } };
const TfArray<1, int> outputs7 = { 1, { 28 } };
const TfLiteConvParams opdata8 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs8 = { 3, { 28,8,7 } };
const TfArray<1, int> outputs8 = { 1, { 29 } };
const ALIGN(1) uint8_t opdata9[1] = { 0,  }; /* op type 40=MEAN */
const TfArray<2, int> inputs9 = { 2, { 29,2 } };
const TfArray<1, int> outputs9 = { 1, { 30 } };
const TfLiteFullyConnectedParams opdata10 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs10 = { 3, { 30,6,5 } };
const TfArray<1, int> outputs10 = { 1, { 31 } };
const TfLiteFullyConnectedParams opdata11 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs11 = { 3, { 31,4,3 } };
const TfArray<1, int> outputs11 = { 1, { 32 } };
const TfLiteSoftmaxParams opdata12 = { 1 };
const TfArray<1, int> inputs12 = { 1, { 32 } };
const TfArray<1, int> outputs12 = { 1, { 33 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 976), (TfLiteIntArray*)&g0::tensor_dimension0, 975, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 192, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 1024, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension5, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 768, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension9, 96, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 216, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension9, 96, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension12, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data13, (TfLiteIntArray*)&g0::tensor_dimension13, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data14, (TfLiteIntArray*)&g0::tensor_dimension14, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data15, (TfLiteIntArray*)&g0::tensor_dimension13, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data16, (TfLiteIntArray*)&g0::tensor_dimension16, 256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data17, (TfLiteIntArray*)&g0::tensor_dimension13, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data18, (TfLiteIntArray*)&g0::tensor_dimension14, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant18))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data19, (TfLiteIntArray*)&g0::tensor_dimension13, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data20, (TfLiteIntArray*)&g0::tensor_dimension20, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant20))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 975, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 8512), (TfLiteIntArray*)&g0::tensor_dimension22, 4256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 4256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4256), (TfLiteIntArray*)&g0::tensor_dimension22, 4256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant24))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 4256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 4256), (TfLiteIntArray*)&g0::tensor_dimension26, 1216, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension27, 1824, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1824), (TfLiteIntArray*)&g0::tensor_dimension28, 480, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension29, 640, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 768), (TfLiteIntArray*)&g0::tensor_dimension30, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant30))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension30, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant31))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension32, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant32))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension32, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant33))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[13] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[13] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_ADD, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_MEAN, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 34, };
const size_t tflNodes_subgraph_index[] = {0, 13, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  33, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_795283_5_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 34;
  for (size_t i = 0; i < 34; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_DEPTHWISE_CONV_2D] = Register_DEPTHWISE_CONV_2D();
  registrations[OP_ADD] = Register_ADD();
  registrations[OP_MEAN] = Register_MEAN();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_795283_5_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_795283_5_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_795283_5_invoke() {
  for (size_t i = 0; i < 13; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_795283_5_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
