/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 19.12.2025 05:23:22

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 10
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 20
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 14672;
#else
constexpr int kTensorArenaSize = 13648;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_RESHAPE, OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_ADD, OP_MEAN, OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,806 } };
const TfArray<1, float> quant0_scale = { 1, { 0.038084272295236588, } };
const TfArray<1, int> quant0_zero = { 1, { -6 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 1, 62, 13, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data2[2] = { 1, 2, };
const TfArray<1, int> tensor_dimension2 = { 1, { 2 } };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[6] = { -619, -445, 67, 74, 1010, 23, };
const TfArray<1, int> tensor_dimension3 = { 1, { 6 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00014007888967171311, } };
const TfArray<1, int> quant3_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[6*24] = { 
  69, -90, -4, -56, 19, -1, -28, -25, -67, 14, -72, 118, 68, -66, 66, 39, 19, -20, 92, -127, 78, -97, -23, -45, 
  -49, 98, -81, 93, 21, -101, -62, 12, 105, -67, -23, -43, -27, 17, -81, 100, -105, -13, -92, 37, 62, -41, 32, -80, 
  54, -77, 12, -76, 7, 24, -82, -95, -67, -27, -63, -3, -69, 29, -24, -26, 37, -27, 33, -49, -34, 84, 78, 91, 
  -4, 85, 26, 62, 51, -14, -2, -28, -24, 1, -121, -36, -125, -119, -86, 33, 7, 22, 96, 15, 82, -73, 11, -74, 
  83, -79, -87, 5, 33, -74, 77, 31, -4, -96, 63, 23, -53, 83, -65, -28, -22, -6, -33, 55, -109, -72, -86, -31, 
  25, -32, 11, 71, -115, 27, -67, 101, 96, 82, 43, -23, 103, -73, -106, -14, -54, -58, -80, -97, -75, 58, -51, 81, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 6,24 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0061989873647689819, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[24] = { 807, -62, 1721, 1615, 2074, 1108, 1012, 126, 463, 330, 3797, -166, 1123, 1292, 163, -267, -347, -519, 391, 2723, -10, 2537, -249, 345, };
const TfArray<1, int> tensor_dimension5 = { 1, { 24 } };
const TfArray<1, float> quant5_scale = { 1, { 5.6032076827250421e-05, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[24*32] = { 
  -59, -9, 70, -22, -29, -54, 46, 69, 32, 34, 72, 40, -43, 49, -87, -30, 95, 13, -41, 111, 49, -31, -46, 84, 72, -51, 35, -12, 22, -4, -10, -15, 
  20, -28, -17, 23, -12, 106, -47, -20, 57, 37, 23, -47, 63, -80, 91, 14, -42, 66, 6, -41, 39, -6, 58, -86, -43, 5, -26, 6, -27, 51, 88, -25, 
  4, 127, 22, 62, 26, -70, -23, -43, 5, 125, -39, 43, 79, -70, 43, 71, 12, 41, -83, 39, 107, 85, 33, -84, 53, 13, -106, 40, -28, -37, 18, 29, 
  66, 29, -72, 69, 50, 69, 4, -21, -1, 5, -29, 20, -16, -50, 105, 65, -13, -12, -17, -69, 76, -38, 67, -69, -90, 10, 44, 87, -82, -15, 58, 94, 
  99, 42, 53, -16, 32, 76, -25, -39, -60, -44, 25, -60, 52, 24, 107, -44, -8, 55, -47, 14, 73, -71, 73, 43, 76, 67, 12, -22, 29, -38, 35, -5, 
  -5, 117, 46, 13, 20, -57, 0, -82, 56, 83, 35, -29, -5, -81, -39, -22, -11, 47, -49, -4, -27, 101, 61, 17, 82, 69, -75, 56, 61, 45, -63, 82, 
  -50, -9, -76, -64, 15, -5, 24, 71, 18, -62, 30, -63, -4, 103, -59, -92, 38, 1, 30, -14, -12, -62, -22, 40, -54, 49, 1, 12, 68, -12, -20, -12, 
  25, 5, -86, 53, -103, 21, 76, -26, 45, 45, -9, -26, 10, 50, 15, 51, 4, -47, -8, -65, 23, 43, -91, 25, -65, -14, 74, 33, -5, 71, -89, 47, 
  43, -54, -31, 10, 18, 67, 51, 53, 71, -9, -43, 22, -62, -68, -21, 62, -9, -35, 50, -88, 31, 51, -50, -46, -105, 35, 94, 78, -59, 49, 29, 67, 
  -17, 56, -49, 35, -67, -32, 77, -21, 30, 0, -63, 24, 58, -65, -50, 47, 50, -22, -36, 2, 73, 65, -41, -14, -61, 23, -4, 31, -69, 14, -16, 47, 
  25, -69, -126, 49, 9, 62, 15, 66, 52, -3, 45, -5, -23, 34, -43, 55, 56, -86, -38, -55, -8, 0, -99, 88, -103, 11, 74, 18, 114, 17, 52, 43, 
  -87, -37, 39, -27, 33, -44, 34, 27, 32, -28, -68, 37, 58, 70, -98, 10, -86, -6, -38, 76, 41, -16, 88, 80, 22, -10, 2, -79, -54, -36, -94, 20, 
  -103, -18, -41, 88, 37, -74, 70, 54, -11, -37, -75, 103, 59, 24, -55, -15, -73, -14, -57, -42, 23, 20, -10, 31, 68, 34, -6, 20, 13, -5, -51, 91, 
  72, -1, -23, 7, -29, -22, -79, 105, -3, -25, 79, -1, -95, 75, 11, -52, 42, 41, 84, 55, -44, 1, -75, 105, -42, 63, 23, -23, 75, -41, 12, 28, 
  -83, 22, 75, -61, 29, -102, 5, -51, 16, -21, -66, 72, 59, 44, -90, 6, 14, -13, 38, 79, 21, -27, 41, 95, 29, -49, -3, -39, 6, 41, -52, -50, 
  51, -22, 69, 59, 69, 13, 34, 32, 17, -55, -25, -43, 0, -1, 34, -10, 1, -19, 41, 27, 24, -28, 64, -66, 13, -55, 84, -25, -77, 35, 7, -37, 
  -69, 72, 96, 33, 26, -22, 15, -49, 34, -13, 65, 42, 53, 24, 16, 32, 17, 9, -86, 85, 66, 19, 16, -25, 98, 43, -59, 21, 77, -14, -17, -83, 
  14, -12, 54, 42, 43, -17, 2, -71, -52, -22, -5, 24, 1, -57, -42, 43, -9, -36, 17, -49, -8, -14, -62, 26, -34, 10, 54, 47, -46, -23, -27, 11, 
  -5, -2, 21, 43, 96, 21, 24, -109, -37, 22, 57, 65, -4, -23, -13, 45, -27, 38, -92, 104, 41, -74, 66, -26, 78, 23, -77, -97, -60, -13, 22, 32, 
  127, -31, 24, -50, 42, 105, -23, 75, -27, -1, 33, -50, -22, 41, 76, -1, 33, 5, 1, -70, 17, 2, 22, -25, -54, 43, 1, 1, 68, -52, 41, -21, 
  66, 34, 52, -60, 44, 32, -45, -75, 67, -54, -51, 37, 39, -25, 77, -22, -80, 20, 9, 9, 6, -68, 115, -37, 68, 7, 70, -39, -2, 45, -54, -5, 
  -37, 119, 16, -17, -95, -96, -10, -29, 14, 63, -28, 2, 19, -39, -74, 72, 0, 62, 84, -47, -9, 87, -50, -46, -60, 49, -8, 58, 94, 62, 81, -16, 
  96, 62, 43, -33, 27, -25, 18, -39, -1, -51, 39, -14, -30, -80, 27, 19, -40, 71, 48, 39, -36, 66, -47, -77, 55, 57, 26, 42, 12, -26, 77, -58, 
  -35, 62, 10, 45, -100, -29, -7, -9, 54, 38, -3, 39, -66, -19, -77, 10, -6, 54, -9, 32, 1, 56, -66, -60, 18, 86, 24, 39, 89, -55, 21, 4, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 24,32 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0049529364332556725, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant3_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data7[32] = { -8761, -2280, -3282, 2611, -2546, -6398, 3077, -2367, 4704, 1774, 2382, 7290, -2105, 1818, -6181, 3334, -1743, -2917, -2493, -435, 2469, -2780, -2803, 131, -2253, 4727, -926, -7721, 1691, 2837, -3545, 517, };
const TfArray<1, int> tensor_dimension7 = { 1, { 32 } };
const TfArray<32, float> quant7_scale = { 32, { 0.00010896167805185542, 0.00016237808449659497, 0.00015916248958092183, 9.7119554993696511e-05, 0.00012267050624359399, 0.00010087946429848671, 0.00015044132305774838, 0.00018433129298500717, 0.00012802043056581169, 0.00016403215704485774, 0.00012593982683029026, 0.00013386753562372178, 0.00015890965005382895, 0.00015671354776713997, 0.00013102105003781617, 9.0886693214997649e-05, 0.00014064056449569762, 0.00019880187755916268, 0.00019406464707572013, 0.00011041758261853829, 0.0001056838154909201, 0.00010502225632080808, 0.00012887490447610617, 0.00013727639452554286, 0.00012441269063856453, 0.00017283036140725017, 0.00019874254940077662, 0.00010258580732624978, 0.00015147343219723552, 0.00012532134132925421, 0.00013807647337671369, 0.00010893451690208167, } };
const TfArray<32, int> quant7_zero = { 32, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data8[32*1*1*24] = { 
  /* [0][0][][] */ 24,97,-11,9,2,39,11,2,58,-2,22,127,53,36,93,25,35,-2,103,-87,44,-13,23,60, 
  /* [1][0][][] */ 65,60,-7,-23,56,41,-65,-2,90,65,31,3,29,-62,63,101,-37,40,-9,9,20,-16,49,-127, 
  /* [2][0][][] */ 27,-9,1,-48,32,35,17,-27,105,33,32,26,-10,-43,22,127,-47,72,-53,24,-10,62,10,3, 
  /* [3][0][][] */ -20,18,72,43,-97,-64,-41,122,-56,40,-93,-127,-1,61,-46,-54,-33,-14,33,-20,30,-74,120,-79, 
  /* [4][0][][] */ -53,39,9,-56,-39,-19,103,-28,-19,15,8,-28,-31,69,-2,75,-14,-54,53,31,9,127,-60,80, 
  /* [5][0][][] */ -43,115,-21,37,-56,5,52,8,5,-19,-3,110,17,127,112,22,67,-57,72,-72,62,10,-68,34, 
  /* [6][0][][] */ -23,-60,127,31,-78,-117,30,29,-1,55,-39,-16,-52,33,-60,-63,-21,34,-5,95,12,39,-47,-95, 
  /* [7][0][][] */ 17,-27,-15,127,33,25,-25,-16,15,-24,18,93,-3,-6,5,-42,-2,-28,-17,17,0,14,24,51, 
  /* [8][0][][] */ 50,34,127,-38,-91,-122,-60,33,8,-50,69,48,6,21,-55,-52,68,-54,-106,-29,107,-116,-38,-39, 
  /* [9][0][][] */ 21,44,49,-18,41,-50,22,72,-73,4,88,-53,-37,-1,118,-36,-127,16,35,7,-9,-62,17,-76, 
  /* [10][0][][] */ -2,36,-18,117,89,-41,19,-115,66,-18,-51,-75,-5,-93,30,57,-18,81,127,-29,-59,-69,-72,-5, 
  /* [11][0][][] */ -6,-110,61,-32,45,-80,127,-95,-34,-25,10,-22,-34,-29,-107,0,-24,-3,-81,65,16,65,-33,-63, 
  /* [12][0][][] */ -67,12,19,-55,-21,61,127,-40,-31,-52,50,-6,-27,-16,-14,8,-3,-22,-12,85,22,43,14,76, 
  /* [13][0][][] */ -14,-96,34,52,62,-75,19,-88,16,33,-69,-31,-71,18,-61,-21,35,14,-17,50,-48,71,-8,127, 
  /* [14][0][][] */ -7,127,-44,-21,-33,11,61,47,-6,0,38,95,53,-11,69,31,12,-81,62,-62,44,-8,-33,75, 
  /* [15][0][][] */ -88,-127,-4,-8,-21,47,-12,-37,12,105,-48,-24,69,11,103,-114,-73,63,49,-42,54,-104,105,-107, 
  /* [16][0][][] */ 63,-15,-59,127,37,-6,17,-51,34,85,49,-10,-73,-47,40,-22,39,82,16,-26,-77,-23,59,17, 
  /* [17][0][][] */ 49,28,-25,-12,59,38,-32,-10,91,26,2,7,-10,-49,56,127,32,56,20,-56,5,8,32,-87, 
  /* [18][0][][] */ 7,-21,4,2,0,4,-88,-11,-12,41,8,127,-30,-6,44,-22,17,34,51,-31,27,23,17,-15, 
  /* [19][0][][] */ 58,-22,40,-54,127,-47,10,-88,92,41,-30,-63,-100,-38,0,93,-7,105,-45,75,-10,114,6,47, 
  /* [20][0][][] */ -75,103,-9,-18,-15,31,109,-47,51,-30,92,-124,60,20,69,-8,-55,-78,33,32,-34,108,-127,-64, 
  /* [21][0][][] */ 82,34,-12,-22,68,-74,-66,74,55,127,3,-50,56,-1,53,-13,-72,88,-69,18,60,-61,109,-23, 
  /* [22][0][][] */ -61,38,38,-71,-33,23,127,-31,-41,-8,2,18,-43,76,-6,64,30,-30,7,51,21,83,-54,44, 
  /* [23][0][][] */ -5,-86,3,98,55,-4,-17,-76,-35,-16,-82,-72,-54,-11,-53,33,65,38,-67,127,-32,122,23,110, 
  /* [24][0][][] */ 31,4,40,-49,28,13,75,-51,47,33,10,-51,-39,-27,21,127,-6,54,-28,33,5,114,-23,-9, 
  /* [25][0][][] */ 8,55,28,-31,94,-106,11,42,127,55,-1,-67,-32,-27,-21,-19,-115,49,110,-62,-88,-80,-84,-43, 
  /* [26][0][][] */ 1,-21,-2,73,-34,-9,-27,5,-4,-27,-63,127,-10,59,-4,-33,9,-41,-10,-24,29,10,44,-12, 
  /* [27][0][][] */ 62,42,52,84,-1,-6,-61,127,-10,116,45,82,92,-24,52,-66,-22,28,-21,44,9,-61,107,-57, 
  /* [28][0][][] */ 95,-20,28,36,127,-10,-88,-88,99,60,-16,10,-71,-67,69,-8,-26,107,18,9,-47,-54,3,-31, 
  /* [29][0][][] */ -41,35,112,7,-103,-11,-103,29,2,43,-53,30,108,51,-42,-100,66,-42,-36,-8,21,59,-127,-114, 
  /* [30][0][][] */ 60,95,-6,-41,82,-76,-82,14,-6,20,22,52,-6,26,127,43,-59,85,83,-75,59,4,-9,-16, 
  /* [31][0][][] */ 7,60,-8,110,-118,-127,67,109,-65,57,-58,-111,8,59,-45,-125,52,-66,17,74,53,-53,100,-35, 
};
const TfArray<4, int> tensor_dimension8 = { 4, { 32,1,1,24 } };
const TfArray<32, float> quant8_scale = { 32, { 0.0046308711171150208, 0.0069010686129331589, 0.0067644054070115089, 0.004127581138163805, 0.0052134962752461433, 0.0042873769998550415, 0.0063937562517821789, 0.0078340796753764153, 0.0054408684372901917, 0.0069713667035102844, 0.0053524426184594631, 0.0056893704459071159, 0.0067536602728068829, 0.0066603259183466434, 0.0055683944374322891, 0.0038626843597739935, 0.005977223627269268, 0.0084490794688463211, 0.0082477470859885216, 0.0046927472576498985, 0.0044915620237588882, 0.0044634458608925343, 0.0054771830327808857, 0.0058342465199530125, 0.0052875392138957977, 0.0073452899232506752, 0.008446558378636837, 0.0043598967604339123, 0.0064376206137239933, 0.0053261569701135159, 0.0058682500384747982, 0.0046297167427837849, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data9[24] = { -529, -2259, -9217, -1528, -2542, 3184, -1983, 3290, -1443, -4735, -3154, -4793, -8071, -889, -1725, -574, 5186, 630, -2014, -5275, -4066, -1691, -8429, 10064, };
const TfArray<24, float> quant9_scale = { 24, { 0.00034821068402379751, 0.00021329299488570541, 9.0263150923419744e-05, 0.00023947429144755006, 0.00022851570975035429, 0.00016140847583301365, 0.00028920269687660038, 0.00017986324382945895, 0.00023010124277789146, 0.00015249225543811917, 0.00019290838099550456, 0.00016418453014921397, 0.00011629942309809849, 0.00023596464598085731, 0.00025017300504259765, 0.00044252048246562481, 0.00017949733592104167, 0.00016627110016997904, 0.00018561288015916944, 0.00012835868983529508, 0.00015270279254764318, 0.00031439718441106379, 0.00010708442277973518, 0.00014788062253501266, } };
const TfArray<24, int> quant9_zero = { 24, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data10[1*3*3*24] = { 
  /* [0][0][][] */ -78,84,86,80,-40,-15,86,-34,81,-8,36,118,102,52,127,66,-127,-10,-25,-119,81,127,59,-103, -59,-7,92,-25,55,-57,-31,31,-4,62,19,53,52,-49,-62,-22,-58,-110,95,117,84,50,127,-127, 127,38,12,2,-117,-127,-11,13,-33,53,30,19,53,-102,-2,-28,-59,87,117,46,-21,10,2,29, 
  /* [0][1][][] */ 45,127,121,127,-26,78,127,-127,-70,55,92,127,127,127,66,127,-23,57,-28,-20,40,115,96,-127, 7,-60,127,-115,95,-34,-83,37,-127,127,7,65,52,-44,-20,-35,-81,-127,127,127,47,74,82,-77, 111,53,8,18,-127,-83,25,19,-40,14,62,64,-19,117,90,-63,-50,105,-90,98,66,41,30,-1, 
  /* [0][2][][] */ -35,115,60,80,37,66,91,-49,57,39,-127,96,71,62,-114,94,-43,36,27,30,54,94,115,-53, -20,-68,6,-34,83,-8,-93,-1,72,101,42,85,80,-12,-14,-6,-35,-110,58,116,-127,58,-34,-89, 98,22,50,18,6,-41,-3,28,24,37,28,39,51,74,115,4,5,89,84,48,42,15,3,15, 
};
const TfArray<4, int> tensor_dimension10 = { 4, { 1,3,3,24 } };
const TfArray<24, float> quant10_scale = { 24, { 0.014798954129219055, 0.0090649519115686417, 0.0038361838087439537, 0.010177657008171082, 0.0097119174897670746, 0.0068598599173128605, 0.012291114777326584, 0.0076441876590251923, 0.0097793024033308029, 0.0064809205941855907, 0.0081986058503389359, 0.0069778421893715858, 0.0049427254125475883, 0.010028497315943241, 0.010632351972162724, 0.018807120621204376, 0.0076286369003355503, 0.0070665217936038971, 0.0078885471448302269, 0.0054552443325519562, 0.0064898687414824963, 0.01336188055574894, 0.0045510879717767239, 0.0062849260866641998, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant9_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data11[24] = { -9039, -3309, -2690, 5427, -646, 5449, -1782, 1096, -7455, 687, 2570, -14, 1074, 839, 1174, -2269, 4680, -2372, 3530, 1043, -3769, -133, -3041, -1393, };
const TfArray<24, float> quant11_scale = { 24, { 7.3714269092306495e-05, 0.00012759452511090785, 0.00011615574476309121, 8.9856686827261001e-05, 9.2471986135933548e-05, 8.6763269791845232e-05, 9.0947374701499939e-05, 0.0001438008330296725, 9.9828837846871465e-05, 0.00011104028089903295, 0.00010146364365937188, 0.00011690000974340364, 0.000122458441182971, 8.0611673183739185e-05, 0.00011525668378453702, 9.3524882686324418e-05, 0.00014280600589700043, 0.00017515312356408685, 0.00012486350897233933, 0.00013978152128402144, 0.00013527250848710537, 0.0001226015156134963, 0.00014708608796354383, 9.6016425231937319e-05, } };
const TfLiteAffineQuantization quant11 = { (TfLiteFloatArray*)&quant11_scale, (TfLiteIntArray*)&g0::quant9_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data12[24*1*1*16] = { 
  /* [0][0][][] */ 63,127,-40,-109,-74,-7,-59,13,73,15,94,-80,113,-27,127,-38, 
  /* [1][0][][] */ -72,-127,-23,82,-11,22,-45,-59,-10,30,45,64,40,57,10,71, 
  /* [2][0][][] */ -75,61,-91,125,93,29,-59,13,94,127,22,-112,55,-62,31,-8, 
  /* [3][0][][] */ -47,84,-55,-41,-82,-115,35,-25,107,-119,30,-65,-23,-3,-127,68, 
  /* [4][0][][] */ 127,-55,60,74,-40,-13,118,-39,-87,11,-59,71,-29,-45,-117,-17, 
  /* [5][0][][] */ 62,-38,-53,60,64,111,-51,-127,-103,27,-60,99,-85,-73,-60,7, 
  /* [6][0][][] */ -117,23,-12,57,-12,67,-51,-31,18,-18,-111,-91,65,-127,111,45, 
  /* [7][0][][] */ -127,93,29,11,123,104,56,-94,-21,-87,24,-39,2,24,-59,23, 
  /* [8][0][][] */ 55,57,100,31,127,-17,-26,-30,4,44,87,-25,-15,-52,-78,96, 
  /* [9][0][][] */ 21,-47,75,-20,80,-54,-88,61,20,83,-21,7,-127,87,-27,-25, 
  /* [10][0][][] */ -87,-15,-112,127,73,47,81,-96,-40,9,100,22,-12,-42,-106,-2, 
  /* [11][0][][] */ 59,-49,8,-14,-2,-77,-107,-25,-9,-38,-122,76,27,127,23,5, 
  /* [12][0][][] */ -82,8,33,54,11,-94,-98,101,-68,84,-69,-13,57,127,-33,-92, 
  /* [13][0][][] */ 48,-123,-21,118,55,44,-84,-82,-9,-60,-17,127,-40,-4,0,-124, 
  /* [14][0][][] */ -36,39,-51,99,8,0,19,-95,-77,-27,39,58,13,-6,-127,63, 
  /* [15][0][][] */ -31,-19,-59,23,-22,-28,127,-98,-79,-76,-26,-18,12,8,126,-2, 
  /* [16][0][][] */ -66,44,-66,9,-79,13,-37,-10,-127,125,-74,-48,0,-59,15,-43, 
  /* [17][0][][] */ -7,59,-22,-1,-13,11,14,-13,15,-42,37,-36,127,32,28,-83, 
  /* [18][0][][] */ -89,66,-50,28,-41,-40,32,-5,-28,-7,-67,81,52,-85,-19,-127, 
  /* [19][0][][] */ 5,-86,-127,-60,54,61,-49,-3,95,1,5,-8,60,35,-109,115, 
  /* [20][0][][] */ 58,5,-70,-71,-42,42,-51,69,-51,92,-5,-58,23,127,79,17, 
  /* [21][0][][] */ 10,45,-127,-9,58,-9,-35,-9,5,-1,-60,-3,41,-107,17,-3, 
  /* [22][0][][] */ 11,-15,60,94,28,-70,98,57,28,76,8,-21,-127,101,-53,50, 
  /* [23][0][][] */ -6,-2,-67,12,-37,97,71,64,-69,127,40,-41,-66,91,27,-27, 
};
const TfArray<4, int> tensor_dimension12 = { 4, { 24,1,1,16 } };
const TfArray<24, float> quant12_scale = { 24, { 0.0031328564509749413, 0.0054227672517299652, 0.004936619196087122, 0.0038189091719686985, 0.0039300592616200447, 0.0036874387878924608, 0.0038652634248137474, 0.0061115352436900139, 0.004242725670337677, 0.004719211719930172, 0.0043122046627104282, 0.0049682501703500748, 0.005204483401030302, 0.0034259960521012545, 0.0048984088934957981, 0.0039748074486851692, 0.0060692550614476204, 0.0074440077878534794, 0.005306699313223362, 0.0059407143853604794, 0.0057490817271173, 0.0052105640061199665, 0.0062511586584150791, 0.0040806978940963745, } };
const TfLiteAffineQuantization quant12 = { (TfLiteFloatArray*)&quant12_scale, (TfLiteIntArray*)&g0::quant9_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data13[16] = { -3358, -503, 8827, -3290, -10237, -6245, 8264, -1678, 1692, -6186, -4582, -2878, -8319, 8102, 10506, -1076, };
const TfArray<1, int> tensor_dimension13 = { 1, { 16 } };
const TfArray<16, float> quant13_scale = { 16, { 0.00011941571574425325, 9.4315590104088187e-05, 0.00011730481492122635, 0.00012535337009467185, 7.2509581514168531e-05, 0.00013040703197475523, 9.7110489150509238e-05, 0.0001145343339885585, 8.2668295362964272e-05, 0.00011383461969671771, 0.00012182535283500329, 0.00013846410729456693, 0.00011332421127008274, 9.0806701336987317e-05, 0.00016729718481656164, 0.00013748007768299431, } };
const TfArray<16, int> quant13_zero = { 16, { 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0 } };
const TfLiteAffineQuantization quant13 = { (TfLiteFloatArray*)&quant13_scale, (TfLiteIntArray*)&quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data14[1*3*3*16] = { 
  /* [0][0][][] */ 30,-55,-25,-87,-68,-17,28,-127,-58,-127,0,103,78,-80,-58,-92, 67,-91,-127,41,72,-1,-35,60,-44,19,114,60,63,-45,-88,38, -61,28,23,76,125,1,-127,53,58,96,-34,-9,78,81,-24,23, 
  /* [0][1][][] */ 37,14,60,-72,32,127,5,-101,-60,15,-61,125,86,-78,6,-61, 77,-75,-72,49,27,41,-119,88,-127,82,127,-127,74,-127,-127,44, -74,127,-56,127,127,17,-77,63,77,94,-57,-7,127,56,-31,17, 
  /* [0][2][][] */ 81,-98,35,-108,110,81,-59,-43,67,93,-52,54,75,-126,-16,-127, 127,15,-68,13,-4,63,-9,41,-122,100,90,-88,50,-119,-87,104, 27,108,-39,87,58,18,11,25,110,2,-13,0,89,33,-12,-2, 
};
const TfArray<4, int> tensor_dimension14 = { 4, { 1,3,3,16 } };
const TfArray<16, float> quant14_scale = { 16, { 0.0050751678645610809, 0.0040084123611450195, 0.0049854544922709465, 0.0053275180980563164, 0.003081657225266099, 0.0055422987788915634, 0.0041271955706179142, 0.0048677092418074608, 0.0035134025383740664, 0.0048379711806774139, 0.0051775774918496609, 0.0058847246691584587, 0.0048162788152694702, 0.0038592847995460033, 0.0071101300418376923, 0.0058429031632840633, } };
const TfLiteAffineQuantization quant14 = { (TfLiteFloatArray*)&quant14_scale, (TfLiteIntArray*)&g0::quant13_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data15[16] = { -576, 4405, -1331, -4868, -5309, 1122, -56, 6041, -1544, 1449, 2826, 1997, -2386, -1901, 730, 2257, };
const TfArray<16, float> quant15_scale = { 16, { 0.00012590346159413457, 0.00018379894027020782, 0.00017058444791473448, 0.00018554396228864789, 0.00022842819453217089, 0.00014403350360225886, 0.00010958735947497189, 0.00017699146701488644, 0.00015254653408192098, 0.00011395651381462812, 0.00017008127178996801, 0.00015600952610839158, 0.00016486342065036297, 0.0001685506576905027, 0.00013266972382552922, 0.0001223803119501099, } };
const TfLiteAffineQuantization quant15 = { (TfLiteFloatArray*)&quant15_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data16[16*1*1*16] = { 
  /* [0][0][][] */ 92,9,113,-102,-42,14,-8,-96,-16,6,13,66,7,-37,-127,-3, 
  /* [1][0][][] */ 34,-125,-54,32,6,-125,70,-20,-11,-46,-94,-118,127,-90,80,-53, 
  /* [2][0][][] */ -63,22,51,-17,127,62,-39,-73,-37,5,57,5,76,-7,32,-58, 
  /* [3][0][][] */ 57,35,-58,-20,41,46,2,-33,62,11,-16,40,-5,127,-36,-81, 
  /* [4][0][][] */ 9,-84,73,93,45,-15,41,48,42,9,-30,32,127,19,-105,2, 
  /* [5][0][][] */ -71,-86,-45,3,5,-30,-3,126,-85,-127,22,107,120,-82,69,8, 
  /* [6][0][][] */ 123,-69,-25,44,-39,42,-127,32,98,-69,-28,23,-47,-38,67,118, 
  /* [7][0][][] */ 6,-10,-64,-42,-127,-34,-99,80,-71,-35,9,82,17,-23,49,-53, 
  /* [8][0][][] */ 110,-93,21,32,-93,-53,102,-61,-70,-16,25,42,40,-87,53,127, 
  /* [9][0][][] */ -82,56,99,21,24,41,-127,62,-36,-71,-72,-108,91,20,63,-21, 
  /* [10][0][][] */ -127,97,44,68,-116,78,-127,6,97,-20,58,-48,39,-14,21,-87, 
  /* [11][0][][] */ 35,67,-63,6,-75,73,88,-60,-80,-16,-89,-127,47,1,-70,-78, 
  /* [12][0][][] */ -6,-13,39,-113,10,-10,73,-45,-55,-50,23,-44,-7,127,-43,51, 
  /* [13][0][][] */ -127,45,36,59,49,-95,68,-67,-69,-27,104,-40,49,-60,78,82, 
  /* [14][0][][] */ -82,25,51,46,78,-22,10,57,78,38,33,110,-40,-127,-115,-97, 
  /* [15][0][][] */ 0,-46,22,95,127,7,-124,-61,-59,-42,-46,-35,82,-58,-90,15, 
};
const TfArray<4, int> tensor_dimension16 = { 4, { 16,1,1,16 } };
const TfArray<16, float> quant16_scale = { 16, { 0.0053508970886468887, 0.0078114545904099941, 0.0072498386725783348, 0.0078856181353330612, 0.0097081977874040604, 0.006121424026787281, 0.0046574627049267292, 0.0075221369042992592, 0.0064832274802029133, 0.0048431516624987125, 0.0072284536436200142, 0.0066304048523306847, 0.0070066950283944607, 0.0071634026244282722, 0.0056384634226560593, 0.0052011632360517979, } };
const TfLiteAffineQuantization quant16 = { (TfLiteFloatArray*)&quant16_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data17[16] = { -7253, 995, -3882, -937, 4331, -2886, -2065, -2451, -663, -6070, 4387, -1229, 654, 5476, 28, -3785, };
const TfArray<16, float> quant17_scale = { 16, { 0.00016987607523333281, 0.00028459404711611569, 0.00019631037139333785, 0.00020778538601007313, 0.0002352087467443198, 0.00016338381101377308, 0.00018032103253062814, 0.00020996321109123528, 0.00033171169343404472, 0.00013161537935957313, 0.00023072936164680868, 0.00025177258066833019, 0.00037401306326501071, 0.00024901804863475263, 0.00022234914649743587, 0.00022523108054883778, } };
const TfLiteAffineQuantization quant17 = { (TfLiteFloatArray*)&quant17_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data18[1*3*3*16] = { 
  /* [0][0][][] */ 52,-81,-8,70,-47,-21,106,-4,103,5,-76,-102,-51,10,127,127, 84,127,77,-93,-23,89,127,90,-127,-91,-87,61,70,-127,-26,114, 125,-57,-94,13,-51,3,-75,-9,29,-12,-54,25,-127,-25,-13,45, 
  /* [0][1][][] */ 127,18,48,43,-34,127,66,-98,88,93,40,99,4,-49,-48,-14, 34,27,73,109,-33,62,-40,-30,-34,4,-31,64,-3,-89,3,-3, 61,-42,-44,-33,-127,-98,-65,39,-33,74,-127,38,1,-12,-13,35, 
  /* [0][2][][] */ 102,-94,17,-127,-14,4,115,127,87,127,98,-3,35,-68,91,-61, 60,56,33,20,68,99,27,45,-13,104,-52,-127,-19,5,-18,38, -29,-94,127,52,-36,-91,-25,49,20,11,-63,8,4,47,-66,2, 
};
const TfArray<16, float> quant18_scale = { 16, { 0.0072197332046926022, 0.012095246464014053, 0.008343190886080265, 0.008830878883600235, 0.0099963713437318802, 0.0069438121281564236, 0.0076636434532701969, 0.0089234365150332451, 0.014097746461629868, 0.0055936537683010101, 0.009805997833609581, 0.010700334794819355, 0.015895554795861244, 0.010583266615867615, 0.0094498386606574059, 0.0095723206177353859, } };
const TfLiteAffineQuantization quant18 = { (TfLiteFloatArray*)&quant18_scale, (TfLiteIntArray*)&g0::quant13_zero, 3 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data19[16] = { 268, 618, -239, -826, -212, -610, 37, 147, -1730, 36, 805, -407, -1182, 1359, -716, -777, };
const TfArray<16, float> quant19_scale = { 16, { 0.00016257943934760988, 0.00011350390559528023, 0.00014816211478319019, 0.00013089073763694614, 0.00015410328342113644, 0.00022244142019189894, 0.00011224700574530289, 0.0001987655705306679, 0.00010764581384137273, 0.00028212676988914609, 0.00012192302529001608, 0.00013548457354772836, 0.00011544721201062202, 0.00015007784531917423, 0.00021095421107020229, 0.00010988314897986129, } };
const TfLiteAffineQuantization quant19 = { (TfLiteFloatArray*)&quant19_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data20[16*3*3*1] = { 
  /* [0][0][][] */ 58, -3, -27, 
  /* [0][1][][] */ 109, -62, 10, 
  /* [0][2][][] */ 127, -21, 20, 
  /* [1][0][][] */ -127, 5, -124, 
  /* [1][1][][] */ -87, -15, -97, 
  /* [1][2][][] */ -41, 43, -40, 
  /* [2][0][][] */ 54, -108, -127, 
  /* [2][1][][] */ 69, -64, -1, 
  /* [2][2][][] */ 48, -86, 42, 
  /* [3][0][][] */ -88, -48, 92, 
  /* [3][1][][] */ 101, 74, 77, 
  /* [3][2][][] */ 64, 73, 127, 
  /* [4][0][][] */ 127, 29, -111, 
  /* [4][1][][] */ 50, 0, -77, 
  /* [4][2][][] */ 58, -44, -34, 
  /* [5][0][][] */ -93, 10, 127, 
  /* [5][1][][] */ -43, -7, 12, 
  /* [5][2][][] */ 106, 23, -76, 
  /* [6][0][][] */ 39, -66, -101, 
  /* [6][1][][] */ -51, -109, -127, 
  /* [6][2][][] */ -81, -61, -66, 
  /* [7][0][][] */ 88, 44, 12, 
  /* [7][1][][] */ -127, -91, 76, 
  /* [7][2][][] */ 83, -3, -10, 
  /* [8][0][][] */ 12, -31, -6, 
  /* [8][1][][] */ -127, -63, -67, 
  /* [8][2][][] */ -125, -34, -28, 
  /* [9][0][][] */ -84, 27, 60, 
  /* [9][1][][] */ 127, 18, -35, 
  /* [9][2][][] */ -78, -43, -39, 
  /* [10][0][][] */ 127, 23, -58, 
  /* [10][1][][] */ 85, 84, -87, 
  /* [10][2][][] */ -93, 36, -52, 
  /* [11][0][][] */ -62, -127, -59, 
  /* [11][1][][] */ -22, -94, -51, 
  /* [11][2][][] */ -61, -14, 44, 
  /* [12][0][][] */ 75, 100, 68, 
  /* [12][1][][] */ 101, 85, 57, 
  /* [12][2][][] */ 65, 127, 1, 
  /* [13][0][][] */ 87, 35, -20, 
  /* [13][1][][] */ 48, 127, 0, 
  /* [13][2][][] */ -35, 50, 57, 
  /* [14][0][][] */ 72, 85, -25, 
  /* [14][1][][] */ -42, -127, 54, 
  /* [14][2][][] */ -22, -86, 56, 
  /* [15][0][][] */ 85, 90, 98, 
  /* [15][1][][] */ 127, 75, 4, 
  /* [15][2][][] */ -52, 93, 75, 
};
const TfArray<4, int> tensor_dimension20 = { 4, { 16,3,3,1 } };
const TfArray<16, float> quant20_scale = { 16, { 0.0042689391411840916, 0.0029803353827446699, 0.0038903753738850355, 0.0034368711058050394, 0.0040463758632540703, 0.0058407685719430447, 0.0029473323374986649, 0.0052190986461937428, 0.0028265162836760283, 0.0074079600162804127, 0.0032014008611440659, 0.0035574939101934433, 0.003031361848115921, 0.0039406777359545231, 0.0055391425266861916, 0.002885263180360198, } };
const TfLiteAffineQuantization quant20 = { (TfLiteFloatArray*)&quant20_scale, (TfLiteIntArray*)&g0::quant13_zero, 0 };
const TfArray<4, int> tensor_dimension21 = { 4, { 1,62,13,1 } };
const TfArray<4, int> tensor_dimension22 = { 4, { 1,31,7,16 } };
const TfArray<1, float> quant22_scale = { 1, { 0.023529412224888802, } };
const TfArray<1, int> quant22_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant22 = { (TfLiteFloatArray*)&quant22_scale, (TfLiteIntArray*)&quant22_zero, 0 };
const TfArray<1, float> quant24_scale = { 1, { 0.069152966141700745, } };
const TfArray<1, int> quant24_zero = { 1, { -7 } };
const TfLiteAffineQuantization quant24 = { (TfLiteFloatArray*)&quant24_scale, (TfLiteIntArray*)&quant24_zero, 0 };
const TfArray<4, int> tensor_dimension26 = { 4, { 1,16,4,16 } };
const TfArray<4, int> tensor_dimension27 = { 4, { 1,16,4,24 } };
const TfArray<4, int> tensor_dimension28 = { 4, { 1,8,2,24 } };
const TfArray<4, int> tensor_dimension29 = { 4, { 1,8,2,32 } };
const TfArray<2, int> tensor_dimension30 = { 2, { 1,32 } };
const TfArray<1, float> quant30_scale = { 1, { 0.011312900111079216, } };
const TfLiteAffineQuantization quant30 = { (TfLiteFloatArray*)&quant30_scale, (TfLiteIntArray*)&g0::quant22_zero, 0 };
const TfArray<2, int> tensor_dimension31 = { 2, { 1,24 } };
const TfArray<1, float> quant31_scale = { 1, { 0.022597059607505798, } };
const TfLiteAffineQuantization quant31 = { (TfLiteFloatArray*)&quant31_scale, (TfLiteIntArray*)&g0::quant22_zero, 0 };
const TfArray<2, int> tensor_dimension32 = { 2, { 1,6 } };
const TfArray<1, float> quant32_scale = { 1, { 0.094022877514362335, } };
const TfArray<1, int> quant32_zero = { 1, { -21 } };
const TfLiteAffineQuantization quant32 = { (TfLiteFloatArray*)&quant32_scale, (TfLiteIntArray*)&quant32_zero, 0 };
const TfArray<1, float> quant33_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant33 = { (TfLiteFloatArray*)&quant33_scale, (TfLiteIntArray*)&g0::quant22_zero, 0 };
const TfLiteReshapeParams opdata0 = { { 0, 0, 0, 0, 0, 0, 0, 0, }, 0 };
const TfArray<2, int> inputs0 = { 2, { 0,1 } };
const TfArray<1, int> outputs0 = { 1, { 21 } };
const TfLiteConvParams opdata1 = { kTfLitePaddingSame, 2,2, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs1 = { 3, { 21,20,19 } };
const TfArray<1, int> outputs1 = { 1, { 22 } };
const TfLiteDepthwiseConvParams opdata2 = { kTfLitePaddingSame, 1,1, 1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs2 = { 3, { 22,18,17 } };
const TfArray<1, int> outputs2 = { 1, { 23 } };
const TfLiteConvParams opdata3 = { kTfLitePaddingSame, 1,1, kTfLiteActNone, 1,1 };
const TfArray<3, int> inputs3 = { 3, { 23,16,15 } };
const TfArray<1, int> outputs3 = { 1, { 24 } };
const TfLiteAddParams opdata4 = { kTfLiteActRelu6 };
const TfArray<2, int> inputs4 = { 2, { 24,22 } };
const TfArray<1, int> outputs4 = { 1, { 25 } };
const TfLiteDepthwiseConvParams opdata5 = { kTfLitePaddingSame, 2,2, 1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs5 = { 3, { 25,14,13 } };
const TfArray<1, int> outputs5 = { 1, { 26 } };
const TfLiteConvParams opdata6 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs6 = { 3, { 26,12,11 } };
const TfArray<1, int> outputs6 = { 1, { 27 } };
const TfLiteDepthwiseConvParams opdata7 = { kTfLitePaddingSame, 2,2, 1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs7 = { 3, { 27,10,9 } };
const TfArray<1, int> outputs7 = { 1, { 28 } };
const TfLiteConvParams opdata8 = { kTfLitePaddingSame, 1,1, kTfLiteActRelu6, 1,1 };
const TfArray<3, int> inputs8 = { 3, { 28,8,7 } };
const TfArray<1, int> outputs8 = { 1, { 29 } };
const ALIGN(1) uint8_t opdata9[1] = { 0,  }; /* op type 40=MEAN */
const TfArray<2, int> inputs9 = { 2, { 29,2 } };
const TfArray<1, int> outputs9 = { 1, { 30 } };
const TfLiteFullyConnectedParams opdata10 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs10 = { 3, { 30,6,5 } };
const TfArray<1, int> outputs10 = { 1, { 31 } };
const TfLiteFullyConnectedParams opdata11 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs11 = { 3, { 31,4,3 } };
const TfArray<1, int> outputs11 = { 1, { 32 } };
const TfLiteSoftmaxParams opdata12 = { 1 };
const TfArray<1, int> inputs12 = { 1, { 32 } };
const TfArray<1, int> outputs12 = { 1, { 33 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 816), (TfLiteIntArray*)&g0::tensor_dimension0, 806, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 8, {kTfLiteNoQuantization, nullptr}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 96, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 768, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data7, (TfLiteIntArray*)&g0::tensor_dimension7, 128, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data8, (TfLiteIntArray*)&g0::tensor_dimension8, 768, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data9, (TfLiteIntArray*)&g0::tensor_dimension5, 96, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data10, (TfLiteIntArray*)&g0::tensor_dimension10, 216, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data11, (TfLiteIntArray*)&g0::tensor_dimension5, 96, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant11))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data12, (TfLiteIntArray*)&g0::tensor_dimension12, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant12))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data13, (TfLiteIntArray*)&g0::tensor_dimension13, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant13))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data14, (TfLiteIntArray*)&g0::tensor_dimension14, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant14))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data15, (TfLiteIntArray*)&g0::tensor_dimension13, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant15))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data16, (TfLiteIntArray*)&g0::tensor_dimension16, 256, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant16))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data17, (TfLiteIntArray*)&g0::tensor_dimension13, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant17))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data18, (TfLiteIntArray*)&g0::tensor_dimension14, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant18))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data19, (TfLiteIntArray*)&g0::tensor_dimension13, 64, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant19))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data20, (TfLiteIntArray*)&g0::tensor_dimension20, 144, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant20))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension21, 806, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 6944), (TfLiteIntArray*)&g0::tensor_dimension22, 3472, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 3472, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3472), (TfLiteIntArray*)&g0::tensor_dimension22, 3472, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant24))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension22, 3472, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 3472), (TfLiteIntArray*)&g0::tensor_dimension26, 1024, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension27, 1536, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 1968), (TfLiteIntArray*)&g0::tensor_dimension28, 384, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension29, 512, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant22))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 640), (TfLiteIntArray*)&g0::tensor_dimension30, 32, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant30))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension31, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant31))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 32), (TfLiteIntArray*)&g0::tensor_dimension32, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant32))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension32, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant33))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[13] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[13] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs4, (TfLiteIntArray*)&g0::outputs4, (TfLiteIntArray*)&g0::inputs4, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata4)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs5, (TfLiteIntArray*)&g0::outputs5, (TfLiteIntArray*)&g0::inputs5, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata5)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs6, (TfLiteIntArray*)&g0::outputs6, (TfLiteIntArray*)&g0::inputs6, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata6)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs7, (TfLiteIntArray*)&g0::outputs7, (TfLiteIntArray*)&g0::inputs7, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata7)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs8, (TfLiteIntArray*)&g0::outputs8, (TfLiteIntArray*)&g0::inputs8, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata8)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs9, (TfLiteIntArray*)&g0::outputs9, (TfLiteIntArray*)&g0::inputs9, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata9)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs10, (TfLiteIntArray*)&g0::outputs10, (TfLiteIntArray*)&g0::inputs10, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata10)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs11, (TfLiteIntArray*)&g0::outputs11, (TfLiteIntArray*)&g0::inputs11, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata11)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs12, (TfLiteIntArray*)&g0::outputs12, (TfLiteIntArray*)&g0::inputs12, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata12)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_RESHAPE, OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_ADD, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_DEPTHWISE_CONV_2D, OP_CONV_2D, OP_MEAN, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 34, };
const size_t tflNodes_subgraph_index[] = {0, 13, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  33, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_822117_6_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 34;
  for (size_t i = 0; i < 34; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_RESHAPE] = Register_RESHAPE();
  registrations[OP_CONV_2D] = Register_CONV_2D();
  registrations[OP_DEPTHWISE_CONV_2D] = Register_DEPTHWISE_CONV_2D();
  registrations[OP_ADD] = Register_ADD();
  registrations[OP_MEAN] = Register_MEAN();
  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_822117_6_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_822117_6_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_822117_6_invoke() {
  for (size_t i = 0; i < 13; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_822117_6_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
